#!/usr/bin/python3

import datetime, os, subprocess

if os.geteuid() != 0:
    print("Need to run as root.  Aborting")
    exit()

script_dir = os.path.dirname(os.path.realpath(__file__))
os.chdir(script_dir)
logfile = open("log.txt", "a")

def log(msg):
    logfile.write(f"{datetime.datetime.now().strftime('%d/%m/%Y %H:%M:%S')} {msg}\n")
    logfile.flush()

log(f"Running {os.path.realpath(__file__)}")

cmd = "/usr/bin/python3 vizy_power_monitor.py"

ret = subprocess.run(f"pgrep -x -f '{cmd}'", shell=True, capture_output=True).returncode

if ret == 0:
    print("vizy_power_monitor.py already running")
else:
    cmdline = f"nohup {cmd} >>log.txt"
    print(f"Starting vizy_power_monitor: {cmdline} &")
    os.popen(f"nohup {cmdline} &")
