#!/usr/bin/python3

import os, subprocess

cmd = "/usr/bin/python3 vizy_power_monitor.py"

if subprocess.run(f"pkill -x -f '{cmd}'", shell=True).returncode == 0:
    print("Stopped vizy_power_monitor")
else:
    print("vizy_power_monitor already stopped")



