#!/usr/bin/python3

import os, subprocess

if os.geteuid() != 0:
    print("Need to run as root.  Aborting")
    exit()

cmd = "/usr/bin/python3 vizy_power_monitor.py"

returncode = subprocess.run(f"pkill -x -f '{cmd}'", shell=True).returncode
if returncode == 0:
    print("Stopped vizy_power_monitor")
else:
    print(f"vizy_power_monitor already stopped (returncode = {returncode})")



